apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service-deployment
spec:
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
      - name: orders-service
        image: orders-service
        env:
        - name: MONGODB_URL
          value: mongodb://orders-db-service:27019/orders
        - name: RABBITMQ_URL
          value: amqp://rabbitmq-service:5672
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3003
      initContainers:
      - image: busybox
        name: init-products-db
        command: ['sh', '-c', "until nslookup orders-db-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for orders-db-service; sleep 2; done"]      
      - image: busybox
        name: init-rabbitmq
        command: ['sh', '-c', "until nslookup rabbitmq-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for rabbitmq-service; sleep 2; done"]      
