apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service-deployment
spec:
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
      - name: products-service
        image: products-service
        env:
        - name: MONGODB_URL
          value: mongodb://products-db-service:27018/products
        - name: RABBITMQ_URL
          value: amqp://rabbitmq-service:5672
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3002    
      initContainers:
      - image: busybox
        name: init-products-db
        command: ['sh', '-c', "until nslookup products-db-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for products-db-service; sleep 2; done"]      
      - image: busybox
        name: init-rabbitmq
        command: ['sh', '-c', "until nslookup rabbitmq-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for rabbitmq-service; sleep 2; done"]      

