{
 "title": "Kubernetes / Horizontal Pod Autoscaler",
 "description": "A quick and simple dashboard for viewing how your horizontal pod autoscaler is doing.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_horizontalpodautoscaler_metadata_generation{job=\"kube-state-metrics\"},namespace)"
    }
   },
   {
    "name": "horizontalpodautoscaler",
    "label": "HPA",
    "query": {
     "query": "label_values(kube_horizontalpodautoscaler_info{job=\"kube-state-metrics\", namespace=\"$namespace\"},horizontalpodautoscaler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Desired Replicas",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{job=\"kube-state-metrics\", namespace=\"$namespace\", horizontalpodautoscaler=\"$horizontalpodautoscaler\"}"
    }
   ]
  },
  {
   "title": "Current Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{job=\"kube-state-metrics\", namespace=\"$namespace\", horizontalpodautoscaler=\"$horizontalpodautoscaler\"}"
    }
   ]
  },
  {
   "title": "Min Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{job=\"kube-state-metrics\",  namespace=\"$namespace\", horizontalpodautoscaler=\"$horizontalpodautoscaler\"}"
    }
   ]
  },
  {
   "title": "Max Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{job=\"kube-state-metrics\", horizontalpodautoscaler=\"$horizontalpodautoscaler\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_target_metric{horizontalpodautoscaler=\"$horizontalpodautoscaler\", metric_target_type=\"utilization\"}",
     "legendFormat": "{{metric_name}}"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{namespace=\"$namespace\", horizontalpodautoscaler=\"$horizontalpodautoscaler\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 18, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_target_metric{horizontalpodautoscaler=\"$horizontalpodautoscaler\", metric_target_type=\"utilization\"}",
     "legendFormat": "{{metric_name}}"
    },
    {
     "expr": "sum(kube_horizontalpodautoscaler_spec_target_metric{namespace=\"$namespace\", horizontalpodautoscaler=\"$horizontalpodautoscaler\"})",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}