apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.8-management-alpine
        resources:
          requests:
            memory: "500Mi"
            cpu: "0.05"
          limits:
            memory: "2Gi"
            cpu: "2"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5672
