apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service-deployment
spec:
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3001"
    spec:
      containers:
      - name: users-service
        image: users-service
        env:
        - name: MONGODB_URL
          value: mongodb://users-db-service:27017/users
        resources:
          requests:
            memory: "64Mi"
            cpu: "150m"
          limits:
            memory: "128Mi"
            cpu: "300m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
